# Generated by Django 6.0 on 2026-03-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('post_id', models.BigIntegerField(blank=True, null=True)),
                ('event_id', models.BigIntegerField(blank=True, null=True)),
                ('relate_url', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('comment', 'Comment'), ('event', 'Event'), ('post_like', 'Postlike'), ('post_dislike', 'Postdislike'), ('notice', 'Notice')], default='comment', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
